package com.joeykot.dictate.advanced_audio

/**
 * Application-controlled workflow contract supplied to the workflow compiler.
 *
 * Keep this beside the schema and validator rather than in the settings UI so
 * every generation entry point receives the same current contract.
 */
object WorkflowSchemaDescription {
    val text: String = """
        Advanced Audio API Workflow Schema v2

        Root fields: schema_version:number (exact version 2), name:string, parameters:ParameterDefinition[], secrets:SecretDefinition[], audio:AudioSpec, recognition:Recognition. ParameterDefinition is id, label, required:boolean, type:text|integer|number|boolean|select|multi_select|json_object|json_array, optional default:string literal, optional description:string, optional options:ParameterOption[], optional visible_when:VisibilityCondition. ParameterOption is value:string plus label:string. select and multi_select require nonempty unique options; their defaults must use declared option values. All parameter defaults and saved values are strings. A multi_select default or saved value is a string whose contents are a JSON string array of unique option values, for example \"[\\\"zh\\\",\\\"en\\\"]\"; never emit an actual JSON array for its default. json_object and json_array defaults or saved values are strings whose contents are respectively a JSON object or JSON array; never emit a raw JSON object or array for their defaults. integer/number/boolean defaults are their JSON textual forms, such as 16000, 0.5, true, or false, stored as strings. VisibilityCondition is parameter:string plus exactly one of equals:string or nonempty one_of:string[]; it may reference only an earlier unconditional boolean/select parameter with a default, and is GUI presentation metadata only: it creates no request branch and never relaxes required values. SecretDefinition is id, label, required:boolean, optional description:string; IDs are ASCII identifiers. Generate schema version 2 only; this build separately retains schema version 1 text-only workflows for existing configurations.
        AudioSpec is delivery:AudioDelivery plus optional mime:string. Delivery type is multipart_file|raw_audio|base64|data_uri|public_https_url|cloud_uri|provider_upload|realtime_chunks.
        Recognition is tagged by mode: request(request:HttpStage, final_text:ResponseExtractor); request_stream(request:HttpStage, stream:StreamResponse); async_poll(optional prepare:HttpStage, submit:HttpStage, optional poll:PollStage, result_steps:HttpStage[] at most 2, final_text:ResponseExtractor); realtime_session(realtime:RealtimeWorkflow). No arbitrary steps, callbacks, branches, or loops exist; only poll repeats.
        HttpStage has method GET|POST|PUT|PATCH|DELETE, url, optional query:string map, headers:string map, body:HttpBody, accepted_statuses:number[] default [200], signer:SignerConfig, captures:Capture[]. A literal HttpStage URL, including async_poll result_steps, must start with http:// or https:// before any template. When an earlier response documents a complete absolute HTTP(S) URL, a later HttpStage URL may be exactly {{capture:id}}; its rendered value is checked for an absolute HTTP(S) URL before the request. Relative paths and other template-only URLs are invalid. HttpBody is tagged none; json(value:any JSON); form_urlencoded(fields:string map); multipart(fields of name plus text(value), bytes(base64 value), or audio_file); raw_audio; raw_bytes(value). Typed audio_file is the only multipart binary audio field. Multipart/raw_audio remain streaming and cannot use a dynamic signer.
        ResponseExtractor is tagged json_path(path), header(name), plain_body, or status. Capture is id, from:ResponseExtractor, optional sensitive:boolean; only a later stage may reference it. A capture used as an entire dynamic HTTP URL is automatically treated as sensitive for redaction.
        StreamResponse has format sse|ndjson|json_chunks and rules:StreamRule[]. StreamRule has optional event, optional JSONPath path, action ignore|append_delta|replace_partial|commit_segment|set_final_text|complete|fail, optional equals. Text actions require path; equals requires path including conditional complete; one complete action is required.
        PollStage has request, interval_ms, timeout_ms, pending/success/failure PollCondition arrays. Poll uses GET or POST only and cannot carry/refer to audio. PollCondition has from, operator eq|ne|exists|not_exists|is_true|is_false|in, value for eq/ne or values for in; each condition array is nonempty.
        SignerConfig is tagged none; aws_sigv4(region, service, access_key_secret, secret_key_secret, optional session_token_secret); or tencent_tc3(service, secret_id_secret, secret_key_secret). Referenced secret IDs must be declared.
        RealtimeWorkflow has transport websocket only, connect, optional initial_messages, audio_stream, audio_message, receive_rules, optional finish_messages, completion, pause_behavior restart_session only, finalization_timeout_ms. Connect has url, optional query/headers, signer, optional subprotocol. RealtimeMessage is tagged json(value), text(value), binary(value). audio_stream supports pcm_s16le and pacing realtime. audio_message text/json must contain {{audio:chunk_base64}}; connect/query/headers/subprotocol/initial/finish may not use audio templates. Realtime receive_rules need an explicit complete action unless completion declares an event or JSONPath completion condition.
        A typed var preserves its native JSON type only when it is the complete value of a JSON leaf, exactly {{var:id}}. In URL, query, header, form, multipart text, raw bytes, realtime text/binary, or a mixed JSON string, vars render as text. multi_select, json_object, and json_array may be used only as that complete JSON leaf; reject them in every other template location before network I/O. json_object and json_array have no text serialization. Templates only allow {{var:id}}, {{secret:id}}, {{capture:id}}, {{audio:filename|mime|size|base64|data_uri|public_url|cloud_uri|chunk_base64}}, {{runtime:uuid|unix_seconds|unix_millis}}. Declarations, stage ordering, and delivery compatibility must validate. No other namespace, expression, code, file/environment access, or executable action exists.
    """.trimIndent()
}
